spring:
  application:
    name: admin-service
  security:
    user:
      name: "user"
      password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8100

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.5:8761/eureka