spring:
  application:
    name: admin-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
  #      resourceserver:
#        jwt:
#          issuerUri: http://localhost:8083/auth/realms/baeldung
#          jwkSetUri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  boot:
    admin:
      client:
        url: http://192.168.1.5:${server.port}
        auto-registration: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8100

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.5:8761/eureka

#  spring.boot.admin.notify.slack.webhook-url=https://hooks.slack.com/services/<Channel_WebHook>
#  spring.boot.admin.notify.slack.channel=test