spring:
  application:
    name: admin-service
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        url: http://192.168.1.5:${server.port}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        auto-registration: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8100

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.5:8761/eureka

#  spring.boot.admin.notify.slack.webhook-url=https://hooks.slack.com/services/<Channel_WebHook>
#  spring.boot.admin.notify.slack.channel=test